# Generated by Django 3.2.15 on 2022-08-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
