# Generated by Django 3.2.15 on 2022-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220808_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, to='auctions.Auction'),
        ),
    ]
