# Generated by Django 3.2.15 on 2022-08-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_watchlist_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='username',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(to='auctions.Auction'),
        ),
    ]
