# Generated by Django 3.2.15 on 2022-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20220808_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(related_name='auction', to='auctions.Auction'),
        ),
    ]
