# Generated by Django 3.2.15 on 2022-08-08 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20220808_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='users_watchlist',
            field=models.ManyToManyField(blank=True, related_name='users_watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
