# Generated by Django 3.2.15 on 2022-08-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auction_users_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
