# Generated by Django 3.2.15 on 2022-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_delete_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
