# Generated by Django 3.2.15 on 2022-08-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Home', 'Home'), ('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Commodity', 'Commodity')], default='All', max_length=30),
        ),
    ]
