# Generated by Django 3.2.15 on 2022-08-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_auction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
