# Generated by Django 3.2.15 on 2022-08-09 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_auction_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='auction',
            name='users_bids',
            field=models.ManyToManyField(blank=True, related_name='users_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
