# Generated by Django 3.2.15 on 2022-08-09 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20220809_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_count',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
