# Generated by Django 3.2.15 on 2022-08-09 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20220809_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='users_bids',
        ),
        migrations.AddField(
            model_name='bids',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='bids',
            name='new_bid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bidding', to=settings.AUTH_USER_MODEL),
        ),
    ]
