# Generated by Django 3.2.15 on 2022-08-09 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20220809_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
