# Generated by Django 3.2.15 on 2022-08-09 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_bids_bid_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='user',
        ),
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
