# Generated by Django 3.2.15 on 2022-08-09 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20220809_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('publish',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.auction'),
        ),
        migrations.AddField(
            model_name='comments',
            name='content',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=1, max_length=254),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='comments',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
